# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu@24.10
    steps:
    - name: Build lint and test
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm run lint
    - run: npm test
